//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityLibraryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReaderToBookView
    {
        public string Fullname { get; set; }
        public string Faculty_Name { get; set; }
        public string Phone { get; set; }
        public System.DateTime Get_Book { get; set; }
        public System.DateTime Deadline { get; set; }
        public string Book_Name { get; set; }
        public string Author_Name { get; set; }
    }
}
