//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityLibraryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader_to_Book
    {
        public int Id { get; set; }
        public Nullable<int> ReaderId { get; set; }
        public Nullable<int> BookId { get; set; }
        public System.DateTime Get_Book { get; set; }
        public System.DateTime Deadline { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
